services:
  db:
    image: postgres:16
    container_name: comparehub_db
    environment:
      POSTGRES_USER: comparehub
      POSTGRES_PASSWORD: comparehub123
      POSTGRES_DB: comparehub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
